import UofT from "../assets/UofTLogo.png";
import Udemy from "../assets/udemyLogo.png";
import OtherIcon from "../assets/otherIcon.png";
import SchoolIcon from "../assets/schoolIcon.png";
import PianoIcon from "../assets/pianoIcon.png";
import OxfordLogo from "../assets/OxfordLogo.jpg";

export const education = [
  {
    title: "Master of Computer Science",
    company: "University of Oxford",
    showLogo: true,
    description: [`~`, `~`, `~`, `~`, `~`, `~`, `~`, `~`, `~`],
    dates: "2024 (Expected)",
    logos: [
      {
        src: OxfordLogo,
        width: "100%",
        height: "100%",
      },
    ],
  },
  {
    title: "Honours Bachelor’s Degree in Computer Science (2022)",
    company: "University of Toronto",
    showLogo: true,
    description: [
      `- Graduated from one of the most competitive programs at the best university in Canada.`,
      `~`,
      `- Computer Science Specialist program.`,
      `~`,
      `- Software Engineering, Computer Systems, Web development, Machine Learning.`,
      `~`,
      `- Activities and societies: University of Toronto Machine Intelligence Club.`,
      `~`,
      `- Member of computer science mentorship program. Mentored first year computer science students.`,
    ],
    dates: "September 2017 - August 2022",
    logos: [
      {
        src: UofT,
        width: "100%",
        height: "100%",
      },
    ],
  },
  {
    title: "School Diploma with Distinction (2017)",
    company: "Russian Public School",
    showLogo: true,
    description: [
      `- Elementary School (2006-2010).`,
      `- Secondary School(2010-2015).`,
      `- High School(2015-2017).`,
      `~`,
      `- Graduated with distinction (red diploma).`,
      `~`,
      `- Some of the classes taken: Algebra, Calculus, Mathematical Analysis, Physics, Chemistry, Biology, English, Russian (as primary language, grades 1-11), Russian Literature (grades 1-11), Information Technology, World History, Geography.`,
      `~`,
      `- Russian schools have 11 grades instead of 12. As most children, I started school at the age of 7.`,
      `~`,
      `- Took SAT and SAT Subjects (Math & Physics Specialty) tests during my final year of school and achieved high scores.`,
      `~`,
      `- The SAT is a standardized test widely used for college admissions in the United States and Canada.`,
      `~`,
      `- Icon by Freepik from flaticon.com.`,
      `~`,
    ],
    dates: "Fall 2006 - Summer 2017",
    logos: [
      {
        src: SchoolIcon,
        width: "100%",
        height: "100%",
      },
    ],
  },
  {
    title: "Music School Diploma (2014)",
    company: "In-school music academy",
    showLogo: true,
    description: [
      `~`,
      `- Attended music school since my first year at primary school as an extra-curricular activity.`,
      `~`,
      `- Piano specialty.`,
      `~`,
      `- Icon by flaticon.com.`,
      `~`,
    ],
    dates: "Fall 2006 - Summer 2014",
    logos: [
      {
        src: PianoIcon,
        width: "100%",
        height: "100%",
      },
    ],
  },
];

export const coursework = [
  {
    title: "ECO105: Introductory Microeconomics and Macroeconomics",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC108: Introduction To Computer Programming",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "MAT223: Linear Algebra",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "MAT137: Calculus with proofs",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC148: Introduction To Computer Science",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title:
      "CSC165: Math Expressions And Reasoning For Computer Science",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC207: Software Design",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC236: Introduction To Theory Of Computation",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title:
      "CSC318: Interactive Computational Media (UX Design Course)",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "STA247: Probability and statistics",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC209: Software Tools And Systems Programming",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title:
      "CSC258: Computer Organization (Computer Architecture Course)",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC263: Data Structures And Analysis",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC343: Introduction To Databases",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC301: Introduction To Software Engineering",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC309: Introduction To Web Development",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC369: Operating Systems",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC384: Introduction To Artificial Intelligence",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC302: Engineering Large-Scale Software Systems",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC311: Introduction To Machine Learning",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC367: Parallel Programming",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title:
      "CSC373: Algorithm Design, Analysis, And Complexity",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC404: Videogame Design",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC420: Introduction To Image Understanding",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC300: Computers And Society",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title:
      "CSC324: Principles Of Programming Languages",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
  {
    title: "CSC443: Database Management Systems",
    company: "",
    showLogo: false,
    description: [],
    dates: "",
    logos: [],
  },
];

export const awards = [];
